services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./banco-api-financa:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

volumes:
  banco-api-financa:
